# Generated by Django 3.1.6 on 2021-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
